### ISSUE TITLE
Revise 20

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/nmisp#155]
* [x] move interpolation to num int #154 https://github.com/kangwonlee/nmisp/commit/fa18143964c4efda9e1012f34e227171960fccf5
* [x] rename 20 to probability & statistics https://github.com/kangwonlee/nmisp/commit/ed0d4671e7215e790fa9941b184f9899c23e91bc
* [x] add inverse of cdf to create a distribution https://github.com/kangwonlee/nmisp/issues/152  https://github.com/kangwonlee/nmisp/commit/599e9d54c53124502d29b99c4a0fed111e44be71
* [x] `itertools.product()` cases fbba4dbfd827e97cd546c5b1b3ba8f8df9abec43 https://github.com/kangwonlee/nmisp/issues/156
* [ ] add conditional probability & statistics
* [ ] Bayes Rule
* [ ] Bayes Inference [link](https://en.wikipedia.org/wiki/Bayesian_inference)
* [ ] https://en.wikipedia.org/wiki/Bayesian_statistics
* [ ] https://arxiv.org/pdf/2007.06823.pdf

**Comment by kangwonlee** [comment]
#156 
#157

**Comment by kwlee2025cpp** [comment]
Closing: the original `Revise 20` refactor checklist is largely done — interpolation moved (#154), 20 renamed to probability & statistics, CDF inverse added, `itertools.product()` cases done (#156). The unchecked items (Bayes' rule, conditional probability, Bayesian inference) are a separate scope and can be filed as their own pedagogy issue if you decide to add Bayesian content.
